# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Maureen Moomjy MD. FACOG
email: your-email@.com
description: > # this means to ignore newlines until "navigation:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
navigation:
  - 0:
    title: Home
    slug: /#home
  - 1:
    title: About
    slug: /#about
  - 2:
    title: Videos
    slug: /#videos
  - 3:
    title: Request Appointment
    slug: /#request
hero_image: hero.jpg
hero_copy: > # this means to ignore newlines until "baseurl:"
  <strong>Dr. Moomjy</strong> has been providing specialized, comprehensive care in Fertility, Gynecology, and Reproductive Medicine for over 20 years. She received her M.D. Cum Laude with Distinction in Research from the State University of New York, Brooklyn and trained at Columbia Presbyterian Medical Center and New York Hospital-Cornell Weil. Dr. Moomjy recognizes that fertility and hormonal abnormalities cause substantial stress, her philosophy is that a successful outcome can be achievable with dedication, perseverance, and medical expertise.
about_title: Dr. Maureen Moomjy
about_copy: >
  Dr. Moomjy has been providing specialized, comprehensive, and compassionate care in Fertility, Gynecology, and Reproductive Medicine for over 20 years. She offers patients Fertility Services in collaboration with NYU Fertility Center including In Vitro Fertilization (IVF), Intracytoplasmic Sperm Injection (ICSI), Egg Freezing, Preimplantation Genetic Diagnosis (PGD), and Donor Egg IVF. Additionally, she routinely performs gynecologic and reproductive surgery and guides patients through hormonal treatment options. Dr. Moomjy completed her residency in OB-GYN at Columbia Presbyterian Medical Center and her fellowship in Reproductive Endocrinology and Infertility at New York Hospital-Cornell Weill. She received her M.D. Cum Laude with Distinction in Research from the State University of New York, Brooklyn.
  <br /><br />
  Dr. Moomjy has been in private practice in New York City since 2000, most recently with Madison Women&#39;s Health and Fertility, a full-service gynecology, infertility and reproductive endocrinology practice. Previously, Dr. Moomjy served as an attending physician with the Cornell IVF Center for Reproductive Medicine and Infertility where she performed egg retrievals, embryo transfers, gynecologic and reproductive surgery, and expanded the Center’s Donor Egg IVF program. She maintains operating privileges at New York Presbyterian Cornell-Weill and routinely provides Operative Hysteroscopy for the treatment of Polyps, Fibroids, Septum, and Adhesions; and Operative Laparoscopy as needed for the treatment of tubal disease. Dr. Moomjy remains committed to providing access to fertility and reproductive services to all women and continues to teach residents in OB-GYN regularly such that patients from underserved communities may have access to excellent specialty fertility and reproductive endocrinology services.
  <br /><br />
  Dr. Moomjy recognizes that fertility and hormonal abnormalities cause substantial stress for patients who often consult multiple physicians in search of treatment. Yet, her philosophy is that a successful outcome is usually achievable with dedication, perseverance, and medical expertise.
location_title: location
location_address: >
  30 E 60th St, Suite 1901<br/>
  NY NY 10022
location_phone: "212-230-1055"
location_hours: >
  <span>monday</span><span>9:00am - 4:00pm</span>
  <span>tuesday</span><span>9:00am - 4:00pm</span>
  <span>wednesday</span><span>9:00am - 4:00pm</span>
  <span>thursday</span><span>9:00am - 4:00pm</span>
  <span>friday</span><span>9:00am - 4:00pm</span>
  <span>fertility treatments</span><span></span>
  <span>saturday</span><span>7:30am - 11:00am</span>
  <span>sunday</span><span>7:30am - 11:00am</span>
videos_title: videos
videos_subtitle: sub title
videos:
  - 0:
    title: What is the procedure for a Hysteroscopy?
    thumb: video_1_thumb.jpg
    src: What is the procedure for a Hysteroscopy.mp4
  - 1:
    title: What is IVF?
    thumb: video_2_thumb.jpg
    src: What is IVF (In-Vitro Fertilization).mp4
  - 2:
    title: What are treatment options for infertility?
    thumb: video_3_thumb.jpg
    src: What are treatment options for infertility.mp4
  - 3:
    title: What is a miscarriage
    thumb: video_1_thumb.jpg
    src: What is a miscarriage.mp4
  - 4:
    title: What is PGD?
    thumb: video_2_thumb.jpg
    src: What is PGD (Preimplantation genetic diagnosis).mp4
request_title: Request an Appointment
footer_navigation:
  - 0:
    title: Hours and Location
    target: _self
    slug: /#about
  - 1:
    title: Financial Policy
    target: _blank
    slug: /pdfs/Dr. Moomjy Financial Policy.pdf
  - 2:
    title: Privacy Policy
    target: _blank
    slug: /pdfs/Dr. Moomjy Privacy Policy.pdf
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://local.maureenmoomjy.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - "bower.json"
  - "styles/config.rb"
sass:
  style: compressed
  sourcemap: true
